#cloud-config

# install ping software
packages:
    - inetutils-ping
package_update: true
package_upgrade: true
package_reboot_if_required: true

final_message: "cloud-init version $VERSION has completed at $TIMESTAMP after $UPTIME using $DATASOURCE"

